In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
type(iris)

sklearn.utils._bunch.Bunch

In [21]:
# convert this dataset into dataframe

df = pd.DataFrame(data = iris.data, columns= iris.feature_names)

In [22]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [23]:
df['target'] = iris.target

In [142]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  flower  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [24]:
df['flower'] = df.target.apply(lambda x:iris.target_names[x])

In [25]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  flower  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [26]:
X = df.iloc[:,:-2]

In [27]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [28]:
y = df.target

In [29]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [54]:
print("X_train",len(X_train))
print("X_test",len(X_test))
print("y_train",len(y_train))
print("y_test",len(y_test))



X_train 120
X_test 30
y_train 120
y_test 30


In [55]:
# Let suppose we choosed support vector machine

from sklearn.svm import SVC
# SVC = scalar vector classifier


In [56]:
model = SVC(kernel = 'rbf', C=30, gamma='auto')

In [57]:
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [58]:
model.score(X_test,y_test)

0.9

In [59]:
# Now there is a problem that the test train split is not happening properly so we will use Kfold so that we get a properly traied data

from sklearn.model_selection import cross_val_score

In [76]:
c1=cross_val_score (SVC(kernel='linear',C=10,gamma='auto'),iris.data, iris.target, cv=5)

In [161]:
c1

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [77]:
c2 =cross_val_score (SVC(kernel='rbf',C=10,gamma='auto'),iris.data, iris.target, cv=5)

In [162]:
c2

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [78]:
c3=cross_val_score (SVC(kernel='linear',C=20,gamma='auto'),iris.data, iris.target, cv=5)

In [163]:
c3

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [79]:
c4=cross_val_score (SVC(kernel='rbf',C=20,gamma='auto'),iris.data, iris.target, cv=5)

In [164]:
c4

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [82]:
print("mean of c1", np.mean(c1))
print("mean of c2", np.mean(c2))
print("mean of c3", np.mean(c3))
print("mean of c4", np.mean(c4))


mean of c1 0.9733333333333334
mean of c2 0.9800000000000001
mean of c3 0.9666666666666666
mean of c4 0.9666666666666668


In [83]:
# As we can see that c2 has the best performance that means the hyperpatameter of c2 is the best but this is still not efficient
# becuase we have to provide all the values manually to the system
# one other manual approach is that we can run a for loop which will be a littlebit convenient

In [167]:
mykernals = ['linear','rbf']
myc = [1,10,20,30]

avg_score = {}
# empty dictionary used to save key-value pair seperated by :

for k in mykernals:
    for c in myc:
        c1=cross_val_score (SVC(kernel=k,C=c,gamma='auto'),iris.data, iris.target, cv=5)
        avg_score[k+'-'+str(c)]= np.mean(c1)

In [168]:
# So as we can see that this process is little bit less manual but it still requires quite a bit of manual labour.
# Also this method is pretty harsh on the system resources imagin if our dataset had 1M data points then this would have taken a lot of time\

avg_score

{'linear-1': np.float64(0.9800000000000001),
 'linear-10': np.float64(0.9733333333333334),
 'linear-20': np.float64(0.9666666666666666),
 'linear-30': np.float64(0.96),
 'rbf-1': np.float64(0.9800000000000001),
 'rbf-10': np.float64(0.9800000000000001),
 'rbf-20': np.float64(0.9666666666666668),
 'rbf-30': np.float64(0.96)}

In [174]:
avg_score['linear-1']

np.float64(0.9800000000000001)

In [176]:
avg_score.items()

dict_items([('linear-1', np.float64(0.9800000000000001)), ('linear-10', np.float64(0.9733333333333334)), ('linear-20', np.float64(0.9666666666666666)), ('linear-30', np.float64(0.96)), ('rbf-1', np.float64(0.9800000000000001)), ('rbf-10', np.float64(0.9800000000000001)), ('rbf-20', np.float64(0.9666666666666668)), ('rbf-30', np.float64(0.96))])

In [111]:
avg_score_df = pd.DataFrame(avg_score.items(),columns=['parametes','Accuracy Score'])

In [113]:
# We can see that Linear-1, rbf-1 and rbf-10 has the best performance

avg_score_df


parametes  Accuracy Score
0   linear-1        0.980000
1  linear-10        0.973333
2  linear-20        0.966667
3  linear-30        0.960000
4      rbf-1        0.980000
5     rbf-10        0.980000
6     rbf-20        0.966667
7     rbf-30        0.960000

In [115]:
# Now to avoide all the overhead issues like manual intervention and system overloading sklearn offers an API callled as
# GridSearchCv that will do all this woek in one line and in a more effective way

from sklearn.model_selection import GridSearchCV

In [116]:
classifier = GridSearchCV(SVC(gamma='auto'),{
    # this is the parameter grid
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False
                         )                          


# What every extra parameter you want just update it in grid 

In [117]:
classifier.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [118]:
classifier.cv_results_

{'mean_fit_time': array([0.00101995, 0.00078478, 0.00084596, 0.00095806, 0.00093932,
        0.0010633 ]),
 'std_fit_time': array([5.79240379e-05, 2.87171591e-05, 9.97943278e-05, 8.74007001e-05,
        2.58304251e-04, 4.82317554e-04]),
 'mean_score_time': array([0.00083156, 0.00062366, 0.00067859, 0.00080957, 0.00078983,
        0.00083127]),
 'std_score_time': array([5.09233063e-05, 5.50046492e-05, 5.97580652e-05, 1.66418259e-04,
        2.00295640e-04, 4.12594207e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [120]:
summary = pd.DataFrame(classifier.cv_results_)

In [121]:
summary

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.001020      0.000058         0.000832        0.000051        1   
1       0.000785      0.000029         0.000624        0.000055        1   
2       0.000846      0.000100         0.000679        0.000060       10   
3       0.000958      0.000087         0.000810        0.000166       10   
4       0.000939      0.000258         0.000790        0.000200       20   
5       0.001063      0.000482         0.000831        0.000413       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [125]:
summary[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [143]:
print(dir(summary))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__'

In [129]:
classifier.best_score_

np.float64(0.9800000000000001)

In [130]:
classifier.best_params_

{'C': 1, 'kernel': 'rbf'}

In [ ]:
# This apporach is some what daunting on the system requirements and take a significant computing when paramentes are more
# So to fix that sklearn has another appraoch called randomized search CV

# Randomized search CV will not try all the permutation and combination instead it will randomly pick some of the parameters and create results

In [135]:
from sklearn.model_selection import RandomizedSearchCV

classifier2 = RandomizedSearchCV(SVC(gamma='auto'),{
    # this is the parameter grid
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False,n_iter=2
                           
)                          


In [137]:
classifier2.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [138]:
classifier2.cv_results_

{'mean_fit_time': array([0.00110116, 0.00113087]),
 'std_fit_time': array([1.21160709e-04, 8.26015473e-05]),
 'mean_score_time': array([0.00096502, 0.00095196]),
 'std_score_time': array([0.00015945, 0.00017713]),
 'param_kernel': masked_array(data=['linear', 'rbf'],
              mask=[False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 1],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 10}, {'kernel': 'rbf', 'C': 1}],
 'split0_test_score': array([1.        , 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      ]),
 'std_test_score': array([0.03887301, 0.01632993]),
 'rank_test_score': array([2, 1], dtype=int32)}

In [140]:
summary2 = pd.DataFrame(classifier2.cv_results_)

In [141]:
summary2

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001101      0.000121         0.000965        0.000159       linear   
1       0.001131      0.000083         0.000952        0.000177          rbf   

   param_C                         params  split0_test_score  \
0       10  {'kernel': 'linear', 'C': 10}           1.000000   
1        1      {'kernel': 'rbf', 'C': 1}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1

In [ ]:
# Now with that being said we also face the problem of which ml algorith to use
# That is we need to find the optimal algo. which gives us the best performance
# so we use grid serach cv as we but this time instead of hyperparameter we use different models


In [151]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [152]:
model_params ={
    'svm':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [ ]:
classifier = GridSearchCV(SVC(gamma='auto'),{
    # this is the parameter grid
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False
                         )          

In [156]:
scores=[]

for model_names, mparams in model_params.items():
    classi = GridSearchCV(mparams['model'],mparams['params'],cv=5, return_train_score=False)
    classi.fit(iris.data, iris.target)
    scores.append({
        'model':model_names,
        'best_score':classi.best_score_,
        'best_params':classi.best_params_
    })

C:\Users\kumaraka\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kumaraka\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kumaraka\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\kumaraka\AppData\Local\Progr

In [157]:
scores

[{'model': 'svm',
  'best_score': np.float64(0.9800000000000001),
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': np.float64(0.9666666666666668),
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': np.float64(0.9666666666666668),
  'best_params': {'C': 5}}]

In [159]:
scores_df = pd.DataFrame(data=scores, columns=['model','best_score','best_params'])

In [160]:
scores_df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [ ]:
# Hence we can conclude that the best model for our iris dataset is SVM since it is giving me the best score of 98%