In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [4]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [5]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [7]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
target = df['spam']
inputs = df['Message']

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target, test_size=0.25)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7526))

In [14]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [15]:
emails = ["Hi jim i just wanted to say thank you for your help last week",
         "Winner!! you have won a $100 amazon gift card click here to redeem"]

emails_count= v.transform(emails)
model.predict(emails_count)

# 1= yes its a spam
# 0=not a spam

array([0, 1])

In [17]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9877961234745154

In [ ]:
# The model is super effective in identifying the spam

In [ ]:
# We can manually test our model as well as shown below
# predict the output and then match it against the y_test

In [19]:
# Here model predicted all the 0(non spam) for the first 10 samples
model.predict(X_test_count[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# The ans for the first 10 samples are also 0
y_test[:10]


507     0
2330    0
4076    0
2350    0
2919    0
1501    0
1843    0
3031    0
3576    0
1763    0
Name: spam, dtype: int64

In [ ]:
# Now you might have noticed that to check any email we have to convert it into numbers by using transform() everytime
# this is inconvient to sklearn provies us a tool called pipeline that will do this task for you
# Pipline can be used to transform data as programmed by the user
# like one process after the another
# Pipeline` allows you to sequentially apply a list of transformers to preprocess the data and, if desired, conclude the sequence with a final
# :term:`predictor` for predictive modeling

In [22]:
 from sklearn.pipeline import Pipeline

In [23]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [24]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [25]:
clf.score(X_test,y_test)

0.9877961234745154

In [26]:
clf.predict(emails)

array([0, 1])